// <auto-generated />
using System;
using IdeaBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdeaBank.Data.Migrations
{
    [DbContext(typeof(IdeaBankDbContext))]
    partial class IdeaBankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdeaBank.Data.Entities.Component", b =>
                {
                    b.Property<Guid>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ComponentId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.Idea", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("IdeaId");

                    b.HasIndex("UserId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaComponent", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.HasKey("IdeaId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("IdeaComponents");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaHelper", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("HelpType")
                        .HasColumnType("integer");

                    b.HasKey("IdeaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("IdeaHelpers");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaPlace", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid");

                    b.HasKey("IdeaId", "PlaceId");

                    b.HasIndex("PlaceId");

                    b.ToTable("IdeaPlaces");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaSector", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.HasKey("IdeaId", "SectorId");

                    b.HasIndex("SectorId");

                    b.ToTable("IdeaSectors");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaUser", b =>
                {
                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer");

                    b.HasKey("IdeaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("IdeaUsers");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.Place", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.Sector", b =>
                {
                    b.Property<Guid>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SectorId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.Idea", b =>
                {
                    b.HasOne("IdeaBank.Data.Entities.User", "Creator")
                        .WithMany("CreatedIdeas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaComponent", b =>
                {
                    b.HasOne("IdeaBank.Data.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaBank.Data.Entities.Idea", "Idea")
                        .WithMany("IdeaComponents")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaHelper", b =>
                {
                    b.HasOne("IdeaBank.Data.Entities.Idea", "Idea")
                        .WithMany("IdeaHelpers")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaBank.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaPlace", b =>
                {
                    b.HasOne("IdeaBank.Data.Entities.Idea", "Idea")
                        .WithMany("IdeaPlaces")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaBank.Data.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaSector", b =>
                {
                    b.HasOne("IdeaBank.Data.Entities.Idea", "Idea")
                        .WithMany("IdeaSectors")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaBank.Data.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.IdeaUser", b =>
                {
                    b.HasOne("IdeaBank.Data.Entities.Idea", "Idea")
                        .WithMany("IdeaUsers")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaBank.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.Idea", b =>
                {
                    b.Navigation("IdeaComponents");

                    b.Navigation("IdeaHelpers");

                    b.Navigation("IdeaPlaces");

                    b.Navigation("IdeaSectors");

                    b.Navigation("IdeaUsers");
                });

            modelBuilder.Entity("IdeaBank.Data.Entities.User", b =>
                {
                    b.Navigation("CreatedIdeas");
                });
#pragma warning restore 612, 618
        }
    }
}
